In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../Analysis Data/earthquake_data.csv")
df

,"In general, how worried are you about earthquakes?","How worried are you about the Big One, a massive, catastrophic earthquake?","Do you think the ""Big One"" will occur in your lifetime?",Have you ever experienced an earthquake?,"Have you or anyone in your household taken any precautions for an earthquake (packed an earthquake survival kit, prepared an evacuation plan, etc.)?",How familiar are you with the San Andreas Fault line?,How familiar are you with the Yellowstone Supervolcano?,Age,What is your gender?,How much total combined money did all members of your HOUSEHOLD earn last year?,US Region
0,Not at all worried,Not so worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Not so familiar,18 - 29,Male,Prefer not to answer,New England
1,Somewhat worried,Very worried,No,"Yes, one or more minor ones",No,Not at all familiar,Not at all familiar,18 - 29,Male,"$75,000 to $99,999",East North Central
2,Not so worried,Somewhat worried,No,"Yes, one or more minor ones",No,Very familiar,Somewhat familiar,18 - 29,Male,"$10,000 to $24,999",Pacific
3,Not so worried,Not so worried,No,"Yes, one or more minor ones",No,Very familiar,Not so familiar,18 - 29,Male,"$25,000 to $49,999",West South Central
4,Not so worried,Not so worried,Yes,"Yes, one or more minor ones",No,Somewhat familiar,Extremely familiar,18 - 29,Male,"$200,000 and up",Middle Atlantic
...,...,...,...,...,...,...,...,...,...,...,...
1008,Not at all worried,Not at all worried,No,"Yes, one or more minor ones",No,Very familiar,Not so familiar,60,Male,Prefer not to answer,Pacific
1009,Not so worried,Somewhat worried,No,"Yes, one or more major ones",Yes,Extremely familiar,Somewhat familiar,60,Female,"$50,000 to $74,999",Pacific
1010,Not so worried,Extremely worried,No,"Yes, one or more minor ones",No,Somewhat familiar,Somewhat familiar,30 - 44,Female,Prefer not to answer,Middle Atlantic
1011,Not at all worried,Not so worried,No,No,No,Somewhat familiar,Somewhat familiar,30 - 44,Female,"$50,000 to $74,999",East North Central
1012,Somewhat worried,Not so worried,No,"Yes, one or more minor ones",No,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_sorted = df[["Age", "What is your gender?", 'Do you think the "Big One" will occur in your lifetime?']]
df_sorted = df_sorted.rename(columns={"What is your gender?": "Gender", 'Do you think the "Big One" will occur in your lifetime?': "Big One"})
df_sorted = df_sorted.sort_values(["Age"])
df_sorted.to_csv(path_or_buf="../Analysis Data/earthquake_data_changed.csv", index=False)

In [20]:
df_sorted = pd.read_csv("../Analysis Data/earthquake_data_changed.csv")
df_sorted

          Age  Gender Big One
0     18 - 29    Male      No
1     18 - 29  Female     Yes
2     18 - 29  Female      No
3     18 - 29  Female      No
4     18 - 29  Female      No
...       ...     ...     ...
1008      NaN     NaN      No
1009      NaN     NaN     Yes
1010      NaN     NaN     Yes
1011      NaN     NaN      No
1012      NaN     NaN      No

[1013 rows x 3 columns]